### ISSUE TITLE
0.1.7-alpha.2 上启动失败：ctx.settings.register is not a function（settings 服务已重构为 SettingsForms）

### ISSUE THREAD

**Issue by zailushang001** [STARDUSTLC666/dsh-email#16]
# dsh-email 在 DSH 0.1.7-alpha.2 上启动失败：`ctx.settings.register is not a function`

## Checklist

- [x] 已确认不是配置错误（`config: {}` 空配置同样失败）
- [x] 已确认不是依赖缺失（`imapflow` / `mailparser` / `nodemailer` / `schemastery` / `yaml` 均可解析）
- [x] 已确认不是包损坏（模块 `import` 正常，`name`/`inject`/`apply` 均存在）
- [x] 已在本地最小复现出确切报错
- [x] 已用反射方式核验新版 settings 服务的 API 面

---

## 环境

| 项目 | 值 |
| --- | --- |
| DSH | `@deepseek-ai/dsh` **0.1.7-alpha.2** |
| profile | `web`（`$DSH_HOME/profiles/web`） |
| 操作系统 | Windows 10 企业版 LTSC 21H2（10.0.19044，64 位） |
| Node | v24 |
| dsh-email | **0.13.2**（**0.10.7 同样复现**） |

## 现象

1. 插件清单 / 插件管理页显示 dsh-email **已启用**，但状态为**启动失败**。
2. 所有 `email_*` 工具（`email_list`、`email_folders`、`email_health`、`email_search`…）**均未注册**，模型侧完全不可见。
3. 同一 profile 内其它第三方插件正常工作：`dsh-cost-meter` 1.7.29 ✅、`dshmarket` 1.57.0 ✅、`dsh-at-file` 0.7.0 ✅。
4. 组件组合层面一切正常：`dsh --profile web --dump-config` 显示该行已挂载、无未匹配 patch、无警告；`cordis.patch.yml` 中的 `tool-email` 覆盖已生效。

> 结论：不是装配问题，而是插件 `apply()` 阶段抛错导致 fiber 启动失败。

## 确切报错

```
TypeError: ctx.settings.register is not a function
    at Module.createEmailRuntime (file:///C:/Users/<user>/.dsh/profiles/web/node_modules/dsh-email/lib/runtime.js:21:40)
```

## 最小复现

```js
// 在 profile 目录下执行
const m = await import(
  'file:///<profile>/node_modules/dsh-email/lib/runtime.js'
)
m.createEmailRuntime({ settings: {} }, {})
// → TypeError: ctx.settings.register is not a function
//   at Module.createEmailRuntime (.../lib/runtime.js:21:40)
```

## 根因

DSH 0.1.7 重构了 settings 服务。`@deepseek-ai/dsh-settings` 现导出 `SettingsForms`，其原型方法（反射实测）为：

```
importLegacyDocument, configure, invalidate, writable, documentPath,
prepareDocument, describe, update, replace, mutate, write, schema
```

**`register` 已不存在。**

而 `lib/runtime.js` 第 21 行**无条件调用**该已移除的 API：

```js
// lib/runtime.js:21
const settingsScope = ctx.settings.register(SETTINGS_NAMESPACE, EmailSettingsSchema, {
  // ...
})
```

值得注意的是，**同一文件第 31 行已经为 API 差异做了防御**，说明作者已察觉部分差异，但第 21 行遗漏：

```js
// lib/runtime.js:31
const descriptor = (ctx.settings.describe?.() ?? []).find(row => row.ns === SETTINGS_NAMESPACE)
```

其它调用点（`lib/web.js`）同样依赖新旧混合的 API 面：

```js
// lib/web.js:788 / 810 / 816
writable: this.ctx.settings.writable !== false
if (this.ctx.settings.writable === false) // ...
await this.ctx.settings.replace(SETTINGS_NAMESPACE, value, expectedRevision)
```

## 版本对照（为什么以前能用）

| DSH 版本 | settings 服务 | dsh-email |
| --- | --- | --- |
| 0.1.6-alpha.1 | 仍提供 `register` | ✅ 正常（`email_*` 工具可用） |
| **0.1.7-alpha.2** | **`SettingsForms`，无 `register`** | ❌ 启动失败，工具不注册 |

DSH 自动升级 0.1.6 → 0.1.7 后立即失效。CHANGELOG 中最近一次兼容性验证是 0.10.8 的「复验 Harness 0.1.5-rc.2 和 0.1.6-alpha.1」，因此 0.1.7 的这次 API 变更尚未被覆盖。

同一轮 DSH 升级还破坏了 `dshmarket` 1.47.0（primitives 图标从 `IconXxx16` 改名为 `IconXxxOutlineMedium/Regular`，抛 React #130），其 1.57.0 已通过改用插件内置图标修复 —— 可作为一个同类先例。

## 期望行为

dsh-email 在 DSH 0.1.7-alpha.2 上正常启动，并注册全部 `email_*` 工具。

## 建议修复方向

将 `ctx.settings.register(ns, schema, opts)` 迁移到 0.1.7 的 `SettingsForms` API。

注意这不是简单改名，语义有实质差异：

- **旧 API**：`register(ns, schema, opts)` 返回一个带 `.get()` 的 scope，插件用它读取命名空间当前值。
- **新 API**：以命名空间描述符为中心，配套 `configure`（注册/声明表单）、`describe`、`update` / `replace` / `mutate`（路径化写入）、`schema`、`writable`。可用 `importLegacyDocument` 处理旧文档迁移。

建议参考 DSH 0.1.7 内置设置消费者（如 `dsh-client-ui-settings-*` 与 `dsh-api-settings-controller` 对应的 host 侧用法）确定命名空间声明与读取的正确姿势。

## 临时绕过（用户侧）

降级 DSH 到 `0.1.6-alpha.1` 可恢复功能，但会失去 0.1.7 的能力，且自动升级可能再次触发。

---

## English abstract

`dsh-email` fails to start on DSH **0.1.7-alpha.2** with:

```
TypeError: ctx.settings.register is not a function
    at Module.createEmailRuntime (.../dsh-email/lib/runtime.js:21:40)
```

The plugin is enabled in the composition but its `apply()` throws, so no `email_*` tools are registered. Root cause: DSH 0.1.7 reworked the settings service — `@deepseek-ai/dsh-settings` now exports `SettingsForms` whose prototype exposes `importLegacyDocument, configure, invalidate, writable, documentPath, prepareDocument, describe, update, replace, mutate, write, schema` — **there is no `register`**. It worked on 0.1.6-alpha.1 (which still had `register`). Both 0.10.7 and 0.13.2 reproduce. A port to the `SettingsForms` API is required; this is not a rename, since the old API returned a scope object with `.get()` while the new one is descriptor + path-addressed writes.
